<?php

declare(strict_types=1);

namespace GooglePlayScraper\Enum;

enum Category: string
{
    case APPLICATION = 'APPLICATION';
    case ANDROID_WEAR = 'ANDROID_WEAR';
    case ART_AND_DESIGN = 'ART_AND_DESIGN';
    case AUTO_AND_VEHICLES = 'AUTO_AND_VEHICLES';
    case BEAUTY = 'BEAUTY';
    case BOOKS_AND_REFERENCE = 'BOOKS_AND_REFERENCE';
    case BUSINESS = 'BUSINESS';
    case COMICS = 'COMICS';
    case COMMUNICATION = 'COMMUNICATION';
    case DATING = 'DATING';
    case EDUCATION = 'EDUCATION';
    case ENTERTAINMENT = 'ENTERTAINMENT';
    case EVENTS = 'EVENTS';
    case FINANCE = 'FINANCE';
    case FOOD_AND_DRINK = 'FOOD_AND_DRINK';
    case HEALTH_AND_FITNESS = 'HEALTH_AND_FITNESS';
    case HOUSE_AND_HOME = 'HOUSE_AND_HOME';
    case LIBRARIES_AND_DEMO = 'LIBRARIES_AND_DEMO';
    case LIFESTYLE = 'LIFESTYLE';
    case MAPS_AND_NAVIGATION = 'MAPS_AND_NAVIGATION';
    case MEDICAL = 'MEDICAL';
    case MUSIC_AND_AUDIO = 'MUSIC_AND_AUDIO';
    case NEWS_AND_MAGAZINES = 'NEWS_AND_MAGAZINES';
    case PARENTING = 'PARENTING';
    case PERSONALIZATION = 'PERSONALIZATION';
    case PHOTOGRAPHY = 'PHOTOGRAPHY';
    case PRODUCTIVITY = 'PRODUCTIVITY';
    case SHOPPING = 'SHOPPING';
    case SOCIAL = 'SOCIAL';
    case SPORTS = 'SPORTS';
    case TOOLS = 'TOOLS';
    case TRAVEL_AND_LOCAL = 'TRAVEL_AND_LOCAL';
    case VIDEO_PLAYERS = 'VIDEO_PLAYERS';
    case WATCH_FACE = 'WATCH_FACE';
    case WEATHER = 'WEATHER';
    case GAME = 'GAME';
    case GAME_ACTION = 'GAME_ACTION';
    case GAME_ADVENTURE = 'GAME_ADVENTURE';
    case GAME_ARCADE = 'GAME_ARCADE';
    case GAME_BOARD = 'GAME_BOARD';
    case GAME_CARD = 'GAME_CARD';
    case GAME_CASINO = 'GAME_CASINO';
    case GAME_CASUAL = 'GAME_CASUAL';
    case GAME_EDUCATIONAL = 'GAME_EDUCATIONAL';
    case GAME_MUSIC = 'GAME_MUSIC';
    case GAME_PUZZLE = 'GAME_PUZZLE';
    case GAME_RACING = 'GAME_RACING';
    case GAME_ROLE_PLAYING = 'GAME_ROLE_PLAYING';
    case GAME_SIMULATION = 'GAME_SIMULATION';
    case GAME_SPORTS = 'GAME_SPORTS';
    case GAME_STRATEGY = 'GAME_STRATEGY';
    case GAME_TRIVIA = 'GAME_TRIVIA';
    case GAME_WORD = 'GAME_WORD';
    case FAMILY = 'FAMILY';
}
